title: Chaitanya
email: hello@chaitanya.page
description: I am Chaitanya. My interests in the field of design include typography, type design, and creative coding.
baseurl: ""
url: "https://chaitanya.page"
permalink: /:categories/:title
markdown: kramdown
plugins:
  - jekyll-feed
feed:
  categories:
    - Blog
    - Haiku
# podcast
podcast_url: https://chaitanya.page/podcast/
podcast_album_art: /assets/images/chaitanya-podcast.png
podcast_title: Chaitanya
podcast_owner: Chaitanya
podcast_email: hellochaitanya@protonmail.com
podcast_category: Personal Journals
podcast_subcategory_one: Philosophy
podcast_subcategory_two: Design
podcast_explicit: "no"
podcast_author: Chaitanya
podcast_description: Weekly short episodes for the highs and lows; small yet impactful ideas. Occasional long candid conversations with guests.
podcast_summary: Weekly short episodes for the highs and lows; small yet impactful ideas. Occasional long candid conversations with guests.
podcast_subtitle:
